// Code generated by logcopter-gen; DO NOT EDIT.

package multi_repository

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var log = logcopter.Package("go-go-golems.clay.pkg.repositories.multi-repository")
