// Code generated by logcopter-gen; DO NOT EDIT.

package yaml_editor

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var log = logcopter.Package("go-go-golems.clay.pkg.yaml-editor")
