// Code generated by logcopter-gen; DO NOT EDIT.

package autoreload

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var log = logcopter.Package("go-go-golems.clay.pkg.autoreload")
