// Code generated by logcopter-gen; DO NOT EDIT.

package map_pool

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var log = logcopter.Package("go-go-golems.clay.pkg.workerpool.map-pool")
