// Code generated by logcopter-gen; DO NOT EDIT.

package filewalker

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var log = logcopter.Package("go-go-golems.clay.pkg.filewalker")
