// Code generated by logcopter-gen; DO NOT EDIT.

package builder

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var log = logcopter.Package("go-go-golems.clay.pkg.filters.command.builder")
